name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      type:
        description: 'Type (edge/proxy)'
        default: 'edge'
        required: true

jobs:
  variables:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: "ARGS: default"
      run: |
        echo "ADDON_LIST=['zigbee2mqtt', 'zigbee2mqtt-edge']" >> $GITHUB_ENV
        echo "DOCKER_ARGS=--no-latest --test" >> $GITHUB_ENV
    - name: "ARGS: zigbee2mqtt" # Build of addon release version
      if: startsWith(github.ref, 'refs/tags/') && github.event_name == 'push'
      run: |
        echo "ADDON_LIST=['zigbee2mqtt']" >> $GITHUB_ENV
        echo "DOCKER_ARGS=--no-cache --docker-hub-check" >> $GITHUB_ENV

    - name: Determine arch
      id: determine_arch
      run: |
        echo $ADDON_LIST
        echo $DOCKER_ARGS

