on:
  workflow_dispatch:

name: Release

permissions: {}
jobs:
  release:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
    - uses: ncipollo/release-action@v1
      with:
        tag: "v1.5.0-1"
        body: "- Updated Zigbee2MQTT to version"
