on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please  

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      version: "${{steps.release.outputs.major}}.${{steps.release.outputs.minor}}.${{steps.release.outputs.patch}}"
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          default-branch: main
          token: ${{secrets.GH_TOKEN}}
          include-v-in-tag: false
          changelog-path: BLA.md
